Repository Dhaigh94/Online-Portfolio, pull requests merged in 2020-01, with the labels that each got.

#18 Add New Qantas Role
  public/images/airlinepage.png
  public/images/qantasairline.jpeg
  server.js
  views/home.ejs
  views/partials/footer.ejs
  views/qantasairline.ejs
  views/work.ejs
Labels: Portfolio Update

#19 Resize Airline image
  public/images/airlinepage.png
Labels: Portfolio Update

#20 Update new Qantas Job
  views/home.ejs
  views/qantasairline.ejs
Labels: Portfolio Update

#21 Resume update
  cypress/integration/Online-Portfolio/home.js
  public/docs/Resume.pdf
  views/home.ejs
Labels: Portfolio Update

#22 Fix Bug on Resume with Qantas Airline Job
  public/docs/Resume.pdf
Labels: Bug

#23 Cleaning the Views folder
  server.js
  views/blogpages/blog.ejs
  views/blogpages/juniortester.ejs
  views/blogpages/mytestingstory.ejs
  views/errorpages/404.ejs
  views/errorpages/500.ejs
  views/other/contact.ejs
  views/other/home.ejs
  views/other/resources.ejs
  views/projectpages/glasscup.ejs
  views/projectpages/imagegallery.ejs
  views/projectpages/patatapclone.ejs
  views/projectpages/photoboard.ejs
  views/projectpages/projects.ejs
  views/projectpages/rawapp.ejs
  views/projectpages/rgbcolourgame.ejs
  views/workpages/aierumbleacademy.ejs
  views/workpages/careerventures.ejs
  views/workpages/covata.ejs
  views/workpages/karteldigital.ejs
  views/workpages/loricahealth.ejs
  views/workpages/play2lead.ejs
  views/workpages/qantasairline.ejs
  views/workpages/qantasloyalty.ejs
  views/workpages/sirc.ejs
  views/workpages/suncorp.ejs
  views/workpages/wired2cloud.ejs
  views/workpages/work.ejs
Labels: Cleanup
